### ISSUE TITLE
Treeshaking / Bundle size decrease

### ISSUE THREAD

**Issue by TheDevMinerTV** [FriendsOfShopware/shopware-admin-vue-standalone#7]
### Please describe the feature you would like to see implemented.

I would like to see the bundle size decrease.
[The current bundle size of this module is 1.7MB minfied, ~500kB minified + gzipped](https://bundlephobia.com/package/shopware-admin-vue-standalone@0.1.3) which is too high in my opinion for a UI library, atleast treeshaking should be supported.

Benefits:
* Smaller bundle size -> faster load time

**Comment by shyim** [comment]
This project will be handled in future in https://github.com/shopware/admin-component-library
